openapi: 3.0.0
info:
  title: Fraud Detection API
  version: '1.0'
  description: API for real-time fraud detection and monitoring
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /predict:
    post:
      summary: Predict fraud probability
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FraudPredictionRequest'
      responses:
        '200':
          description: Fraud prediction result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FraudPredictionResponse'

  # ... keep existing code (other endpoints)

components:
  schemas:
    FraudPredictionRequest:
      type: object
      properties:
        transaction_amount:
          type: number
          format: float
        merchant_id:
          type: string
        customer_id:
          type: string
        timestamp:
          type: string
          format: date-time
        location:
          type: string
        device_id:
          type: string
        ip_address:
          type: string
        transaction_type:
          type: string
        card_present:
          type: boolean
        recurring:
          type: boolean
      required:
        - transaction_amount
        - merchant_id
        - customer_id
        - timestamp
        - location
        - device_id
        - ip_address
        - transaction_type
        - card_present
        - recurring

    FraudPredictionResponse:
      type: object
      properties:
        probability:
          type: number
          format: float
          description: Probability of fraud (0-1)
        is_fraudulent:
          type: boolean
          description: True if transaction is likely fraudulent
        confidence:
          type: number
          format: float
          description: Confidence in the prediction (0-1)

    # ... keep existing code (other schemas)

  # ... keep existing code (security schemes)