name: Publish React Native SDK

on:
  push:
    tags:
      - 'rn-v*.*.*'  # Will trigger on tags like rn-v1.0.0, rn-v1.2.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        working-directory: ./sdks/react-native

      - name: Lint
        run: npm run lint
        working-directory: ./sdks/react-native
        if: ${{ false }}  # Disabled until lint script is added

      - name: Test
        run: npm test
        working-directory: ./sdks/react-native
        if: ${{ false }}  # Disabled until test script is added

      - name: Fix clean script
        run: |
          sed -i 's/"clean": "rimraf dist ist"/"clean": "rimraf dist"/g' package.json
        working-directory: ./sdks/react-native

      - name: Build
        run: npm run build
        working-directory: ./sdks/react-native

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF_NAME#rn-v}" >> $GITHUB_OUTPUT

      - name: Update package version
        run: npm version ${{ steps.extract_version.outputs.VERSION }} --no-git-tag-version
        working-directory: ./sdks/react-native

      - name: Publish to NPM
        run: npm publish --access public
        working-directory: ./sdks/react-native
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: React Native SDK v${{ steps.extract_version.outputs.VERSION }}
          body: |
            Release of React Native SDK version ${{ steps.extract_version.outputs.VERSION }}
            
            ## Changes
            <!-- Add release notes here -->
            
            ## Installation
            ```bash
            npm install @udene/react-native-sdk
            # or
            yarn add @udene/react-native-sdk
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}