name: Publish Ruby SDK

on:
  push:
    tags:
      - 'rb-v*.*.*'  # Will trigger on tags like rb-v1.0.0, rb-v1.2.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ./sdks/ruby

      - name: Run tests
        run: bundle exec rake test
        working-directory: ./sdks/ruby
        if: ${{ false }}  # Disabled until tests are added

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF_NAME#rb-v}" >> $GITHUB_OUTPUT

      - name: Update version in files
        run: |
          # Update version in version.rb
          sed -i "s/VERSION = \".*\"/VERSION = \"${{ steps.extract_version.outputs.VERSION }}\"/g" lib/udene_sdk/version.rb
        working-directory: ./sdks/ruby

      - name: Build gem
        run: gem build udene_sdk.gemspec
        working-directory: ./sdks/ruby

      - name: Setup credentials
        run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF
          chmod 0600 ~/.gem/credentials
        working-directory: ./sdks/ruby

      - name: Publish to RubyGems
        run: |
          gem_file=$(ls udene_sdk-*.gem | head -n 1)
          gem push $gem_file
        working-directory: ./sdks/ruby

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Ruby SDK v${{ steps.extract_version.outputs.VERSION }}
          body: |
            Release of Ruby SDK version ${{ steps.extract_version.outputs.VERSION }}
            
            ## Changes
            <!-- Add release notes here -->
            
            ## Installation
            ```ruby
            # In your Gemfile
            gem 'udene_sdk'
            
            # Or install directly
            gem install udene_sdk
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}