import type { ProfileTable } from './profile';
import type { ClientServicesTable } from './client-services';
import type { EventTriggersTable } from './event-triggers';
import type { AdminDataExtractionsTable } from './admin-data-extractions';
import type { WhitelistTable } from './whitelist';
import type { APIKeysTable, ClientAPIKeysTable, APICreditsTable } from './auth-tables';
import type { AIActivityMonitoringTable, MetricsTable, AuditLogsTable } from './monitoring-tables';
import type { FraudAlertsTable, EmailReputationTable } from './fraud-tables';
import type { TransactionsTable, RewardsTransactionsTable, AffiliateActivitiesTable } from './transaction-tables';
import type { MLModelsTable, TrainingDatasetsTable } from './ml-tables';
import type { UserActivitiesTable, UserNotificationsTable } from './user-tables';
import type { SecurityProgramsTable, SecurityAssessmentsTable, ComplianceReportsTable } from './security-tables';
import type { WebhooksTable, WebhookDeliveriesTable } from './webhook-tables';
import type { ReferralTrackingTable } from './referral-tables';
import type { TrialUsageTable } from './trial-tables';
import type { InvestigationLogsTable } from './investigation-logs';
import type { PromoCodeTable, PromoCodeUsageTable } from './promo-tables';
import type { DeviceFingerprintTable, DeviceFingerprintHistoryTable } from './device-fingerprint-tables';
import type { IdentityVerificationsTable, VerificationAttemptsTable } from './verification-tables';
import type { OpenSourceScanTable } from './open-source-security';

export interface Tables {
  profiles: ProfileTable;
  client_services: ClientServicesTable;
  event_triggers: EventTriggersTable;
  admin_data_extractions: AdminDataExtractionsTable;
  whitelist: WhitelistTable;
  api_keys: APIKeysTable;
  client_api_keys: ClientAPIKeysTable;
  api_credits: APICreditsTable;
  ai_activity_monitoring: AIActivityMonitoringTable;
  metrics: MetricsTable;
  audit_logs: AuditLogsTable;
  fraud_alerts: FraudAlertsTable;
  email_reputation: EmailReputationTable;
  transactions: TransactionsTable;
  rewards_transactions: RewardsTransactionsTable;
  ml_models: MLModelsTable;
  training_datasets: TrainingDatasetsTable;
  user_activities: UserActivitiesTable;
  user_notifications: UserNotificationsTable;
  product_security_programs: SecurityProgramsTable;
  security_assessments: SecurityAssessmentsTable;
  compliance_reports: ComplianceReportsTable;
  webhooks: WebhooksTable;
  webhook_deliveries: WebhookDeliveriesTable;
  affiliate_activities: AffiliateActivitiesTable;
  referral_tracking: ReferralTrackingTable;
  trial_usage: TrialUsageTable;
  service_investigation_logs: InvestigationLogsTable;
  promo_codes: PromoCodeTable;
  promo_code_usage: PromoCodeUsageTable;
  device_fingerprints: DeviceFingerprintTable;
  device_fingerprint_history: DeviceFingerprintHistoryTable;
  identity_verifications: IdentityVerificationsTable;
  verification_attempts: VerificationAttemptsTable;
  open_source_scans: OpenSourceScanTable;
}

export * from './profile';
export * from './client-services';
export * from './event-triggers';
export * from './admin-data-extractions';
export * from './whitelist';
export * from './auth-tables';
export * from './monitoring-tables';
export * from './fraud-tables';
export * from './transaction-tables';
export * from './ml-tables';
export * from './user-tables';
export * from './security-tables';
export * from './webhook-tables';
export * from './referral-tables';
export * from './trial-tables';
export * from './investigation-logs';
export * from './promo-tables';
export * from './device-fingerprint-tables';
export * from './verification-tables';
export * from './open-source-security';